package es.regueiro.easyrepair.ui.client;

import es.regueiro.easyrepair.model.client.Vehicle;
import es.regueiro.easyrepair.reports.ReportPrinter;
import java.util.Collection;
import javax.swing.SwingWorker;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//es.regueiro.easyrepair.ui.client//VehicleDetailedView//EN",
autostore = false)
@TopComponent.Description(iconBase = "es/regueiro/easyrepair/ui/client/icons/mechanic_detailed.png", preferredID = "VehicleDetailedViewTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(position = 1, mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "es.regueiro.easyrepair.ui.client.VehicleDetailedViewTopComponent")
@TopComponent.OpenActionRegistration(displayName = "#CTL_VehicleDetailedViewAction",
preferredID = "VehicleDetailedViewTopComponent")
@Messages({
    "CTL_VehicleDetailedViewAction=Vista detallada de vehículos",
    "CTL_VehicleDetailedViewTopComponent=Vista detallada de vehículos",
    "HINT_VehicleDetailedViewTopComponent=Esta es una ventana de la vista detallada de vehículos"
})
public final class VehicleDetailedViewTopComponent extends TopComponent implements LookupListener {

    private Lookup.Result<Vehicle> result = null;
    private Vehicle vehicle;

    public VehicleDetailedViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_VehicleDetailedViewTopComponent());
        setToolTipText(Bundle.HINT_VehicleDetailedViewTopComponent());
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        generalPanel = new javax.swing.JPanel();
        insuranceNumberLabel = new javax.swing.JLabel();
        registrationTextField = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        insuranceNumberTextField = new javax.swing.JTextField();
        fuelLabel = new javax.swing.JLabel();
        fuelTextField = new javax.swing.JTextField();
        tittleLabel = new javax.swing.JLabel();
        vinLabel = new javax.swing.JLabel();
        ownerNifTextField = new javax.swing.JTextField();
        registrationLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        ownerNifLabel = new javax.swing.JLabel();
        makeTextField = new javax.swing.JTextField();
        colourTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        ownerTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        colourLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        vinTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        insuranceCompanyLabel = new javax.swing.JLabel();
        insuranceCompanyTextField = new javax.swing.JTextField();
        notesLabel = new javax.swing.JLabel();
        notesScrollPane = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        mainScrollPane.setBorder(null);

        mainPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        generalPanel.setMinimumSize(new java.awt.Dimension(100, 192));
        generalPanel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(insuranceNumberLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.insuranceNumberLabel.text_1")); // NOI18N
        insuranceNumberLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(insuranceNumberLabel, gridBagConstraints);

        registrationTextField.setEditable(false);
        registrationTextField.setBackground(new java.awt.Color(232, 231, 231));
        registrationTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        registrationTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(registrationTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(yearLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.yearLabel.text_1")); // NOI18N
        yearLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(yearLabel, gridBagConstraints);

        insuranceNumberTextField.setEditable(false);
        insuranceNumberTextField.setBackground(new java.awt.Color(232, 231, 231));
        insuranceNumberTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        insuranceNumberTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(insuranceNumberTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(fuelLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.fuelLabel.text_1")); // NOI18N
        fuelLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(fuelLabel, gridBagConstraints);

        fuelTextField.setEditable(false);
        fuelTextField.setBackground(new java.awt.Color(232, 231, 231));
        fuelTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        fuelTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(fuelTextField, gridBagConstraints);

        tittleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tittleLabel.setForeground(new java.awt.Color(82, 107, 134));
        org.openide.awt.Mnemonics.setLocalizedText(tittleLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.tittleLabel.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        generalPanel.add(tittleLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(vinLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.vinLabel.text_1")); // NOI18N
        vinLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(vinLabel, gridBagConstraints);

        ownerNifTextField.setEditable(false);
        ownerNifTextField.setBackground(new java.awt.Color(232, 231, 231));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(ownerNifTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(registrationLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.registrationLabel.text_1")); // NOI18N
        registrationLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(registrationLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(modelLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.modelLabel.text_1")); // NOI18N
        modelLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(modelLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(typeLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.typeLabel.text_1")); // NOI18N
        typeLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(typeLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(ownerNifLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.ownerNifLabel.text_1")); // NOI18N
        ownerNifLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(ownerNifLabel, gridBagConstraints);

        makeTextField.setEditable(false);
        makeTextField.setBackground(new java.awt.Color(232, 231, 231));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(makeTextField, gridBagConstraints);

        colourTextField.setEditable(false);
        colourTextField.setBackground(new java.awt.Color(232, 231, 231));
        colourTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        colourTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(colourTextField, gridBagConstraints);

        typeTextField.setEditable(false);
        typeTextField.setBackground(new java.awt.Color(232, 231, 231));
        typeTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        typeTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(typeTextField, gridBagConstraints);

        ownerTextField.setEditable(false);
        ownerTextField.setBackground(new java.awt.Color(232, 231, 231));
        ownerTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        ownerTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(ownerTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(idLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.idLabel.text")); // NOI18N
        idLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(idLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(makeLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.makeLabel.text")); // NOI18N
        makeLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(makeLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(colourLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.colourLabel.text_1")); // NOI18N
        colourLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(colourLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(ownerLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.ownerLabel.text_1")); // NOI18N
        ownerLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(ownerLabel, gridBagConstraints);

        idTextField.setEditable(false);
        idTextField.setBackground(new java.awt.Color(232, 231, 231));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(idTextField, gridBagConstraints);

        vinTextField.setEditable(false);
        vinTextField.setBackground(new java.awt.Color(232, 231, 231));
        vinTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        vinTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(vinTextField, gridBagConstraints);

        modelTextField.setEditable(false);
        modelTextField.setBackground(new java.awt.Color(232, 231, 231));
        modelTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        modelTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(modelTextField, gridBagConstraints);

        yearTextField.setEditable(false);
        yearTextField.setBackground(new java.awt.Color(232, 231, 231));
        yearTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        yearTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(yearTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(insuranceCompanyLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.insuranceCompanyLabel.text_1")); // NOI18N
        insuranceCompanyLabel.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(insuranceCompanyLabel, gridBagConstraints);

        insuranceCompanyTextField.setEditable(false);
        insuranceCompanyTextField.setBackground(new java.awt.Color(232, 231, 231));
        insuranceCompanyTextField.setMinimumSize(new java.awt.Dimension(180, 20));
        insuranceCompanyTextField.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(insuranceCompanyTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(notesLabel, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.notesLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(notesLabel, gridBagConstraints);

        notesTextArea.setEditable(false);
        notesTextArea.setBackground(new java.awt.Color(232, 231, 231));
        notesTextArea.setColumns(20);
        notesTextArea.setRows(3);
        notesScrollPane.setViewportView(notesTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(notesScrollPane, gridBagConstraints);

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/client/icons/printer.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(printButton, org.openide.util.NbBundle.getMessage(VehicleDetailedViewTopComponent.class, "VehicleDetailedViewTopComponent.printButton.text")); // NOI18N
        printButton.setEnabled(false);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        generalPanel.add(printButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(generalPanel, gridBagConstraints);

        mainScrollPane.setViewportView(mainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(mainScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        final SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected void done() {
            }

            @Override
            protected Void doInBackground() {
                ReportPrinter printer = new ReportPrinter();
                printer.printVehicle(vehicle);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_printButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JTextField fuelTextField;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel insuranceCompanyLabel;
    private javax.swing.JTextField insuranceCompanyTextField;
    private javax.swing.JLabel insuranceNumberLabel;
    private javax.swing.JTextField insuranceNumberTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField makeTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JScrollPane notesScrollPane;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JLabel ownerNifLabel;
    private javax.swing.JTextField ownerNifTextField;
    private javax.swing.JTextField ownerTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel registrationLabel;
    private javax.swing.JTextField registrationTextField;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField vinTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public HelpCtx getHelpCtx() {
        //HelpCtx ctx = new HelpCtx("sdk.scene_explorer");
        //this call is for single components:
        return new HelpCtx("es.regueiro.easyrepair.ui.vehicle.detailed");
    }

    @Override
    public void componentOpened() {
        result = VehicleLookup.getDefault().lookupResult(Vehicle.class);
        result.addLookupListener(this);
        fillData();
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
        result = null;

    }

    @Override
    public void resultChanged(LookupEvent event) {
        fillData();
    }

    private void fillData() {
        Collection<? extends Vehicle> vehicleCol = result.allInstances();
        if (!vehicleCol.isEmpty()) {
            Vehicle tempVehicle = vehicleCol.iterator().next();
            if (vehicle != tempVehicle) {
                vehicle = tempVehicle;
                clearGeneral();


                idTextField.setText(vehicle.getId().toString());
                registrationTextField.setText(vehicle.getRegistration());
                vinTextField.setText(vehicle.getVin());
                makeTextField.setText(vehicle.getMake());
                modelTextField.setText(vehicle.getModel());
                yearTextField.setText(vehicle.getYear());
                colourTextField.setText(vehicle.getColour());
                typeTextField.setText(vehicle.getType());
                fuelTextField.setText(vehicle.getFuel());
                insuranceNumberTextField.setText(vehicle.getInsuranceNumber());
                notesTextArea.setText(vehicle.getNotes());

                if (vehicle.getOwner() != null) {
                    String text = vehicle.getOwner().getName();
                    if (vehicle.getOwner().getSurname() != null) {
                        text += " " + vehicle.getOwner().getSurname();
                    }

                    ownerTextField.setText(text);
                    if (vehicle.getOwner().getNif() != null) {
                        ownerNifTextField.setText(vehicle.getOwner().getNif().getNumber());
                    }
                }
                if (vehicle.getInsuranceCompany() != null) {
                    insuranceCompanyTextField.setText(vehicle.getInsuranceCompany().getName());

                }
                printButton.setEnabled(true);
            }
        } else {
//            clear();
        }
    }

    private void clear() {
        vehicle = null;
        clearGeneral();
    }

    private void clearGeneral() {
        idTextField.setText("");
        registrationTextField.setText("");
        vinTextField.setText("");
        makeTextField.setText("");
        modelTextField.setText("");
        yearTextField.setText("");
        colourTextField.setText("");
        typeTextField.setText("");
        fuelTextField.setText("");
        ownerTextField.setText("");
        ownerNifTextField.setText("");
        insuranceCompanyTextField.setText("");
        insuranceNumberTextField.setText("");
        notesTextArea.setText("");
        
        printButton.setEnabled(false);
    }
}
