/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.regueiro.easyrepair.shared.options;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import org.apache.commons.lang3.StringUtils;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbPreferences;

final class ShopDataPanel extends javax.swing.JPanel {

    private final ShopDataOptionsPanelController controller;
    private DialogDescriptor chooseLogoDialog;
    private BufferedImage logo;
    private Image resizedLogo;
    private String imagePath = "";

    ShopDataPanel(ShopDataOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()

        jFileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                // Allow only directories, or files with ".txt" extension
                return file.isDirectory() || file.getAbsolutePath().endsWith(".png")
                        || file.getAbsolutePath().endsWith(".jpg")
                        || file.getAbsolutePath().endsWith(".gif")
                        || file.getAbsolutePath().endsWith(".bmp");
            }

            @Override
            public String getDescription() {
                // This description will be displayed in the dialog,
                // hard-coded = ugly, should be done via I18N
                return java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/shared/options/Bundle").getString("IMAGE_FILES");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser = new javax.swing.JFileChooser();
        jPanel = new javax.swing.JPanel();
        shopNameLabel = new javax.swing.JLabel();
        addressLine1Label = new javax.swing.JLabel();
        addressLine2Label = new javax.swing.JLabel();
        addressLine3Label = new javax.swing.JLabel();
        phoneLineLabel = new javax.swing.JLabel();
        emailLineLabel = new javax.swing.JLabel();
        shopNameTextField = new javax.swing.JTextField();
        addressLine1TextField = new javax.swing.JTextField();
        addressLine2TextField = new javax.swing.JTextField();
        addressLine3TextField = new javax.swing.JTextField();
        phoneLineTextField = new javax.swing.JTextField();
        emailLineTextField = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        chooseLogoButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(shopNameLabel, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.shopNameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(shopNameLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(addressLine1Label, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.addressLine1Label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine1Label, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(addressLine2Label, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.addressLine2Label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine2Label, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(addressLine3Label, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.addressLine3Label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine3Label, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(phoneLineLabel, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.phoneLineLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(phoneLineLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(emailLineLabel, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.emailLineLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(emailLineLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(shopNameTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine1TextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine2TextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(addressLine3TextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(phoneLineTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(emailLineTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(logoLabel, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.logoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(logoLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(logoImage, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.logoImage.text")); // NOI18N
        logoImage.setMaximumSize(new java.awt.Dimension(128, 128));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel.add(logoImage, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chooseLogoButton, org.openide.util.NbBundle.getMessage(ShopDataPanel.class, "ShopDataPanel.chooseLogoButton.text")); // NOI18N
        chooseLogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLogoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel.add(chooseLogoButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(jPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseLogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLogoButtonActionPerformed
//        chooseLogoDialog = new DialogDescriptor(jFileChooser, java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/shared/options/Bundle").getString("SELECT_X"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/shared/options/Bundle").getString("LOGO")), true, NotifyDescriptor.OK_CANCEL_OPTION, NotifyDescriptor.OK_OPTION,
//                new ActionListener() {
//
//                    @Override
//                    public void actionPerformed(ActionEvent e) {
//                        if (e.getSource() == DialogDescriptor.OK_OPTION) {
//                            
//                            chooseLogoDialog.setClosingOptions(null);
//                        } else {
//                        }
//                    }
//                });
//        chooseLogoDialog.setClosingOptions(new Object[]{DialogDescriptor.CANCEL_OPTION});
//        chooseLogoDialog.setValid(false);
//        DialogDisplayer.getDefault().createDialog(jFileChooser.show);
//        DialogDisplayer.getDefault().notify(chooseLogoDialog);
//        new JFileChooser().showOpenDialog(this);
//        
        int ret = jFileChooser.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {

            imagePath = jFileChooser.getSelectedFile().getAbsolutePath();
            logoImage.setIcon(new ImageIcon(loadAndResizeImage(imagePath)));

        }
    }//GEN-LAST:event_chooseLogoButtonActionPerformed

    private Image loadAndResizeImage(String path) {
        Image img = null;
        BufferedImage bimg = null;
        try {
            bimg = ImageIO.read(new File(path));
            float width = bimg.getWidth();
            float height = bimg.getHeight();
            if (width > 256 || height > 256) {
                if (width > height) {
                    float proportion = width / 256;
                    img = bimg.getScaledInstance(256, Math.round(height / proportion), Image.SCALE_SMOOTH);
                } else {
                    float proportion = height / 256;
                    img = bimg.getScaledInstance(Math.round(width / proportion), 256, Image.SCALE_SMOOTH);
                }
            } else {
                img = bimg;
            }
        } catch (IOException e) {
        }
        return img;
    }

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(ShopDataPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(ShopDataPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        shopNameTextField.setText(NbPreferences.root().get("shopName", ""));
        addressLine1TextField.setText(NbPreferences.root().get("address1", ""));
        addressLine2TextField.setText(NbPreferences.root().get("address2", ""));
        addressLine3TextField.setText(NbPreferences.root().get("address3", ""));
        phoneLineTextField.setText(NbPreferences.root().get("phone", ""));
        emailLineTextField.setText(NbPreferences.root().get("email", ""));
        if (!StringUtils.isEmpty(NbPreferences.root().get("logo", ""))) {
            Image im = loadAndResizeImage(NbPreferences.root().get("logo", ""));
            if (im != null) {
                logoImage.setIcon(new ImageIcon(im));
            }
        }

    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(ShopDataPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(ShopDataPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.root().put("shopName", shopNameTextField.getText());
        NbPreferences.root().put("address1", addressLine1TextField.getText());
        NbPreferences.root().put("address2", addressLine2TextField.getText());
        NbPreferences.root().put("address3", addressLine3TextField.getText());
        NbPreferences.root().put("phone", phoneLineTextField.getText());
        NbPreferences.root().put("email", emailLineTextField.getText());
        if (!imagePath.equals("")) {
            NbPreferences.root().put("logo", imagePath);
        }

    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLine1Label;
    private javax.swing.JTextField addressLine1TextField;
    private javax.swing.JLabel addressLine2Label;
    private javax.swing.JTextField addressLine2TextField;
    private javax.swing.JLabel addressLine3Label;
    private javax.swing.JTextField addressLine3TextField;
    private javax.swing.JButton chooseLogoButton;
    private javax.swing.JLabel emailLineLabel;
    private javax.swing.JTextField emailLineTextField;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel phoneLineLabel;
    private javax.swing.JTextField phoneLineTextField;
    private javax.swing.JLabel shopNameLabel;
    private javax.swing.JTextField shopNameTextField;
    // End of variables declaration//GEN-END:variables
}
