package es.regueiro.easyrepair.ui.user;

import es.regueiro.easyrepair.api.user.controller.UserController;
import es.regueiro.easyrepair.login.SecurityManager;
import es.regueiro.easyrepair.model.user.Privilege;
import es.regueiro.easyrepair.model.user.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.ActionMap;
import javax.swing.SwingWorker;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.text.DefaultEditorKit;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.awt.StatusDisplayer;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//es.regueiro.easyrepair.ui.user//UserBrowser//EN",
autostore = false)
@TopComponent.Description(preferredID = "UserBrowserTopComponent",
iconBase = "es/regueiro/easyrepair/ui/user/icons/ceo.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(position = 26, mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "es.regueiro.easyrepair.ui.user.UserBrowserTopComponent")
@ActionReferences({
    @ActionReference(path = "Menu/Usuarios", position = 0),
    @ActionReference(path = "Toolbars/Usuarios", position = 0)
})
@TopComponent.OpenActionRegistration(displayName = "#CTL_UserBrowserAction",
preferredID = "UserBrowserTopComponent")
@Messages({
    "CTL_UserBrowserAction=Buscador de usuarios",
    "CTL_UserBrowserTopComponent=Buscador de usuarios",
    "HINT_UserBrowserTopComponent=Esta es una ventana del buscador de usuarios"
})
public final class UserBrowserTopComponent extends TopComponent implements TableModelListener, ListSelectionListener {

    private UserTableModel model = new UserTableModel();
    private InstanceContent content = new InstanceContent();
    private UserController controller = Lookup.getDefault().lookup(UserController.class);
    private User user;
    private UserLookup lookup = UserLookup.getDefault();

    public UserBrowserTopComponent() {
        initComponents();
        setName(Bundle.CTL_UserBrowserTopComponent());
        setToolTipText(Bundle.HINT_UserBrowserTopComponent());
        this.setFocusable(true);

        String[] inCBStrings = {java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("NAME"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("ROLE")};

        for (String s : inCBStrings) {
            inCombobox.addItem(s);
        }

        // Associate the table model
        userTable.setModel(model);

        // Listen for intro on the search bar
        searchEntryField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                doSearch();
            }
        });


        // Activate Copy/Paste
        ActionMap actionMap = getActionMap();
        actionMap.put(DefaultEditorKit.copyAction, new DefaultEditorKit.CopyAction());
        actionMap.put(DefaultEditorKit.cutAction, new DefaultEditorKit.CutAction());
        actionMap.put(DefaultEditorKit.pasteAction, new DefaultEditorKit.PasteAction());
        content.add(actionMap);

        // Listen to the changes on the table
        model.addTableModelListener(this);
        userTable.getSelectionModel().addListSelectionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchPanel = new javax.swing.JPanel();
        searchEntryPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchEntryField = new javax.swing.JTextField();
        inLabel = new javax.swing.JLabel();
        listAllButton = new javax.swing.JButton();
        inCombobox = new javax.swing.JComboBox();
        searchButtonPanel = new javax.swing.JPanel();
        findButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        topToolBar = new javax.swing.JToolBar();
        newUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        searchPanel.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        searchPanel.setLayout(new java.awt.GridBagLayout());

        searchEntryPanel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(searchLabel, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.searchLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchEntryPanel.add(searchLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchEntryPanel.add(searchEntryField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(inLabel, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.inLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchEntryPanel.add(inLabel, gridBagConstraints);

        listAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/user/icons/group.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(listAllButton, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.listAllButton.text")); // NOI18N
        listAllButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        listAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchEntryPanel.add(listAllButton, gridBagConstraints);

        inCombobox.setPreferredSize(new java.awt.Dimension(79, 31));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchEntryPanel.add(inCombobox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        searchPanel.add(searchEntryPanel, gridBagConstraints);

        searchButtonPanel.setLayout(new java.awt.BorderLayout(5, 5));

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/user/icons/find32.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(findButton, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.findButton.text")); // NOI18N
        findButton.setMargin(new java.awt.Insets(5, 15, 5, 15));
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        searchButtonPanel.add(findButton, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 10, 10);
        searchPanel.add(searchButtonPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(searchPanel, gridBagConstraints);

        tablePanel.setMinimumSize(new java.awt.Dimension(100, 100));

        userTable.setAutoCreateRowSorter(true);
        userTable.setDoubleBuffered(true);
        userTable.setFillsViewportHeight(true);
        userTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        userTable.setRowHeight(25);
        userTable.setSelectionBackground(new java.awt.Color(186, 216, 247));
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePanel.setViewportView(userTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 7);
        add(tablePanel, gridBagConstraints);

        topToolBar.setBorder(null);
        topToolBar.setFloatable(false);
        topToolBar.setRollover(true);

        newUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/user/icons/add.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(newUserButton, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.newUserButton.text")); // NOI18N
        newUserButton.setFocusable(false);
        newUserButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newUserButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        topToolBar.add(newUserButton);

        editUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/user/icons/ceo_edit.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(editUserButton, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.editUserButton.text")); // NOI18N
        editUserButton.setEnabled(false);
        editUserButton.setFocusable(false);
        editUserButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editUserButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });
        topToolBar.add(editUserButton);

        deleteUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/regueiro/easyrepair/ui/user/icons/cross.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteUserButton, org.openide.util.NbBundle.getMessage(UserBrowserTopComponent.class, "UserBrowserTopComponent.deleteUserButton.text")); // NOI18N
        deleteUserButton.setEnabled(false);
        deleteUserButton.setFocusable(false);
        deleteUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        deleteUserButton.setMargin(new java.awt.Insets(5, 5, 5, 5));
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });
        topToolBar.add(deleteUserButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(topToolBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        doSearch();
    }//GEN-LAST:event_findButtonActionPerformed

    private void listAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllButtonActionPerformed
        doListAll();
    }//GEN-LAST:event_listAllButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        lookup.clear();
        editUserButton.setEnabled(false);
        deleteUserButton.setEnabled(false);
        userTable.clearSelection();
        openUserEditor();
    }//GEN-LAST:event_newUserButtonActionPerformed
    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        openUserEditor();
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        NotifyDescriptor d = new NotifyDescriptor.Confirmation(
                java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("SURE_DELETE_X"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("USER")),
                java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("DELETE"), NotifyDescriptor.YES_NO_OPTION);

        Object retval = DialogDisplayer.getDefault().notify(d);

        if (retval == NotifyDescriptor.YES_OPTION) {

            UserEditorTopComponent window = (UserEditorTopComponent) WindowManager.getDefault().findTopComponent("UserEditorTopComponent");
            if (window.getUser() != null && user.getId().equals(window.getUser().getId())) {
                window.forceClose();
            }


            final SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected void done() {
                    StatusDisplayer.getDefault().setStatusText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("X_DELETED"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("USER")));
                    lookup.clear();
                }

                @Override
                protected Void doInBackground() {
                    model.removeRow(userTable.convertRowIndexToModel(userTable.getSelectedRow()));
                    controller.setUser(user);
                    controller.deleteUser();
                    user = null;
                    return null;
                }
            };


            worker.execute();

        }
    }//GEN-LAST:event_deleteUserButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JButton findButton;
    private javax.swing.JComboBox inCombobox;
    private javax.swing.JLabel inLabel;
    private javax.swing.JButton listAllButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JPanel searchButtonPanel;
    private javax.swing.JTextField searchEntryField;
    private javax.swing.JPanel searchEntryPanel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JToolBar topToolBar;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public HelpCtx getHelpCtx() {
        //HelpCtx ctx = new HelpCtx("sdk.scene_explorer");
        //this call is for single components:
        return new HelpCtx("es.regueiro.easyrepair.ui.user.browser");
    }

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
        model.clear();
    }

    @Override
    public void componentActivated() {
        if (SecurityManager.getDefault().isUserLoggedIn()) {
            newUserButton.setEnabled(SecurityManager.getDefault().userHasPrivilege(Privilege.USER_EDIT));
        } else {
            this.close();
        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void tableChanged(TableModelEvent e) {
    }

    @Override
    public void valueChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting()) {
            if (userTable.getSelectedRow() > -1) {
                user = model.getRow(userTable.convertRowIndexToModel(userTable.getSelectedRow()));
                editUserButton.setEnabled(SecurityManager.getDefault().userHasPrivilege(Privilege.USER_EDIT));
                deleteUserButton.setEnabled(SecurityManager.getDefault().userHasPrivilege(Privilege.USER_EDIT));
                lookup.setUser(user);
            } else {
                editUserButton.setEnabled(false);
                deleteUserButton.setEnabled(false);
            }
        }
    }

    private void openUserEditor() {
        TopComponent window = WindowManager.getDefault().findTopComponent("UserEditorTopComponent");
        if (window == null) {
            window = new UserEditorTopComponent();
        } else {
            window.close();
        }
        window.open();
        window.requestActive();
    }

    private void doSearch() {
        final ProgressHandle p = ProgressHandleFactory.createHandle(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("SEARCHING"));

        final SwingWorker<List<User>, Void> worker = new SwingWorker<List<User>, Void>() {
            private int column;

            @Override
            protected void done() {
                try {
                    List<User> list = get();
                    model.fill(list);

                    if (column != 1) {
                        userTable.getRowSorter().toggleSortOrder(column - 1);
                    } else {
                        userTable.getRowSorter().toggleSortOrder(2);
                    }

                    userTable.getRowSorter().toggleSortOrder(column);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                } catch (ExecutionException e) {
                    throw new RuntimeException(e);
                }
                p.finish();
            }

            @Override
            protected List<User> doInBackground() {
                int selected = inCombobox.getSelectedIndex();
                String toSearch = searchEntryField.getText();
                List<User> list = null;
                column = 0;
                if (!toSearch.isEmpty()) {
                    p.setDisplayName(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("SEARCHING_FOR_X"), new Object[]{toSearch}));
                }
                try {
                    switch (selected) {
                        case 0:
                            list = controller.searchByName(toSearch);
                            column = 1;
                            break;
                        case 1:
                            list = controller.searchByRole(toSearch);
                            column = 2;
                            break;
                        default:
                            //this should never happen
                            list = null;
                    }
                } catch (Exception e) {
                    NotifyDescriptor d = new NotifyDescriptor.Message(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("ERROR_SEARCH"), NotifyDescriptor.ERROR_MESSAGE);
                    Object retval = DialogDisplayer.getDefault().notify(d);
                    p.finish();
                }
                return list;
            }
        };
        p.start();
        worker.execute();
    }

    private void doListAll() {

        final ProgressHandle p = ProgressHandleFactory.createHandle(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("LISTING_ALL_X"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("USERS")));

        SwingWorker<List<User>, Void> worker = new SwingWorker<List<User>, Void>() {
            @Override
            protected void done() {
                try {
                    model.fill(get());
                    userTable.getRowSorter().toggleSortOrder(0);
                    userTable.getRowSorter().toggleSortOrder(1);

                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                } catch (ExecutionException e) {
                    throw new RuntimeException(e);
                }
                p.finish();
            }

            @Override
            protected List<User> doInBackground() {
                List<User> list = null;
                try {
                    list = controller.listAll();
                } catch (Exception e) {
                    p.finish();
                    NotifyDescriptor d = new NotifyDescriptor.Message(e.getMessage(), NotifyDescriptor.ERROR_MESSAGE);
                    Object retval = DialogDisplayer.getDefault().notify(d);
                }
                return list;
            }
        };

        p.start();
        worker.execute();
    }

    public void deleteUser(User emp) {
        if (user != null && emp.getId().equals(user.getId())) {
            user = null;
            StatusDisplayer.getDefault().setStatusText(java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("X_DELETED"), java.util.ResourceBundle.getBundle("es/regueiro/easyrepair/ui/user/Bundle").getString("USER")));
            lookup.clear();

        }

        model.removeUser(emp);

    }
}
